[versions]
agp = "8.11.1"
annotation = "1.9.1"
commonsLang3 = "3.18.0"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

